INSERT INTO `category` (SKU, SKU_Category) Values
('FP7634','Dry'),
('FPS7681','Damp'),
('FPD5534','Damp'),
('FPD7617','Wet'),
('MAD6721','Damp'),
('FP9044','Wet'),
('FP3075','Dry'),
('FP3073','Dry'),
('FP3070','Dry'),
('FPS8553','Damp'),
('FP3050','Dry'),
('FP8519','Damp'),
('FP8404','Damp'),
('FP7910','Dry'),
('FP8533','Dry'),
('FP8094','Dry'),
('FP8274','Dry'),
('FP320','Dry'),
('FP6272','Dry'),
('FP8014','Dry')



INSERT INTO `products` (SKU, Name, Finish, Blade_Span, Bulb_Type, Close_to_Ceiling_Kit, Control_Type, Energy_Star, Collection, Light_Kit_Included, Location_Rating, Motor_Size, Motor_Type, Number_of_Blades) Values
('FP7634','Amped','Black - Black + brushed brass - Brushed nickel - Matte white - Matte white + brushed brass', 52,'LED','Not compatible','Remote Control','No','Amped','Yes','Dry','172 x 15','AC Motor', 3),
('FPS7681','Klinch 44','Black - Brushed nickel - Matte white', 44,'LED','Not compatible','Remote Control','No','Klinch','Yes','Damp','172 x 17','AC Motor', 3),
('FPD5534','Kute5','Black - Brushed nickel - Brushed satin brass - Brushed satin brass + black - Dark bronze - Matte greige - Matte white', 52,'','Compatible','Remote Control','Yes','Kute','No','Damp','DC100 x 30','DC Motor', 5),
('MAD6721','Spitfire DC 64','Black - Brushed nickel - Brushed satin brass - Dark bronze - Driftwood - Galvanized - Matte greige - Matte white', 64,'LED','Compatible','Remote Control','No','Spitfire','No','Damp','DC153-25FS','DC Motor', 3),
('FP9044','Edgewood','Black - Brushed nickel - Dark bronze - Matte white', 44,'','Dual Mount','','No','Edgewood','No','Wet','153 x 18','AC Motor', 5),
('FP3075','Influencer','Black - Brushed satin brass - Chrome', 12,'LED','Not compatible','Remote Control','No','Kerring','Yes','Dry','79.5 x 64','AC Motor', 3),
('FP3073','Kerring','Brushed satin brass - Chrome', 14,'LED','Not compatible','Remote Control','No','Kerring','Yes','Dry','79.5 x 64','AC Motor', 3),
('FP3070','Klout','Brushed satin brass - Chrome', 12,'LED','Not compatible','Remote Control','No','Klout','Yes','Dry','79.5 x 64','AC Motor', 3),
('FPS8553','Kwartet','Black - Brushed nickel - Brushed satin brass - Matte greige - Matte white', 52,'LED','Not compatible','Remote Control','No','Kwartet','Yes','Damp','153 x 20','AC Motor', 4),
('FP3050','Obvi','Black - Brushed nickel', 22,'LED','Compatible','Remote Control','No','Obvi','Yes','Dry','DC 153×12','DC Motor', 3),
('FP8404','Gleam','Black - Brushed nickel', 16,'LED','Compatible','Remote Control','','Gleam','Yes','Damp','82 x 30','AC Motor', 4),
('FP7910','Levon AC','Black - Brushed nickel - Brushed nickel + black - Dark bronze - Matte greige - Matte white - Oil-rubbed bronze', 63,'','Compatible','Pull Chain','No','Levon','No','Dry','188 x 25','AC Motor', 8),
('FP8533','Doren','Black - Brushed nickel - Dark bronze - Matte greige - Polished nickel', 52,'LED','Compatible','Remote Control','No','Doren','Yes','Dry','172 x 20','AC Motor', 5),
('FP8094','Camhaven v2','Brushed nickel - Dark bronze - Matte greige - Matte white', 52,'LED','Compatible','Remote Control','No','Camhaven v2','Yes','Dry','172 x 17','AC Motor', 3),
('FP8274','Stafford','Brushed nickel - Dark bronze - Matte greige', 52,'LED','Compatible','Remote Control','No','Stafford','No','Dry','172 x 17','AC Motor', 5),
('FP320','Islander – Dry Finishes','Antique brass - Pewter', '48 – 72','','Not compatible','Pull Chain','No','Islander','No','Dry','FK-2100','AC Motor', 5),
('FP8014','Arden','Oil-rubbed bronze - Satin nickel', 12,'','Not compatible','Other','No','Arden','No','Dry','82 x 25','AC Motor', '')
